### ISSUE TITLE
Observables?

### ISSUE THREAD

**Issue by tycho01** [PolymerLabs/lit-html#109]
First off, congratulations on the current progress of this project!

I'm coming from an Angular background, and am trying to better understand how new Polymer will work with `lit-html` compared to that.

Specifically, Angular 2+ came with this `async` pipe resolving Promises/Observables in the view. Fortunately `lib-html` has already clarified how it works with [`Promises`](https://github.com/PolymerLabs/lit-html/#promises), so currently I'm curious particularly how it might deal with Observables.

Angular itself used RxJS, although the [`Observable` proposal](https://github.com/tc39/proposal-observable) appears about to advance to [stage 2](https://github.com/tc39/proposals). In the Angular context this was relevant notably as a way to ensure trigger re-renders when (and only when) a value had changed, i.e. their [`ChangeDetectionStrategy`](https://angular.io/api/core/ChangeDetectionStrategy) `OnPush`. (In fact, their state management solution meant to facilitate that, [`ngrx`](https://github.com/ngrx/platform), was inspired by [`redux-observable`](https://github.com/redux-observable/redux-observable/).)

How might `Observable`s work over here?

**Comment by justinfagnani** [comment]
Observable support should be easily added via directives.

I have some in-progress directives for async iterables, which might be easily adopted to work with observables (note: it's a shame there are so many stream APIs). I made them directives instead of built-in because there's likely to be some opinion on how they should behave. My first built-in support for async iterables incrementally appended new content, like a streaming version of iterables, but hen moving to directives I created two: one that appends, the other that replaces.

I'll create a PR soon.

**Comment by tycho01** [comment]
I just found a bit more info on Observables as used elsewhere [here](https://medium.com/@milankinen/containers-are-dead-long-live-observable-combinators-2cb0c1f06c96).

**Comment by justinfagnani** [comment]
Since the async iterables support is now merged, and I think Observables can be converted to async iterables, I'm going to close this. Let's open a new issue if something specific comes up.

**Comment by goodmind** [comment]
@justinfagnani but they can't. They are push based, and async iterables are pull based

**Comment by justinfagnani** [comment]
They're both push based. A new value is pushed to an async iterator subscriber by resolving the current Promise.

**Comment by Dabolus** [comment]
For those who don't want to convert observables to async iterables, writing a directive to handle them it's quite straight-forward. I tried to simply take the `asyncReplace` directive and tweak it to make it handle observables and it seems to work great, check it out [here](https://stackblitz.com/edit/lit-html-observables).

**Comment by yorrd** [comment]
@Dabolus will have a look at your package, thanks for the work! I believe there is still a memory leak issue in `asyncReplace` so that won't be solved if you use that internally.

**Comment by Stradivario** [comment]
@yorrd what memory leak issue ? Can you please provide some more detals about it ? Is it still valid ?

**Comment by yorrd** [comment]
@Stradivario it's still valid, observables are not unsubscribed when a part is unloaded so everything is kept in memory. There's another issue on the `lit-html` trackers where unmounting of parts is discussed. We have monkey patched `lit-html` in the meanwhile for our internal needs

**Comment by Stradivario** [comment]
@yorrd @Dabolus check this out
Since i am working with Decorators and i can apply some things when component is mounted and unmounted i decided to implement logic which collects all observables onConnectedCallback from THIS(representing Component decorated with @customElement() decorator) then onDisconnectedCallback i am unsubscribing from all observables.

Define `new Map()` inside the component

```typescript
cls.subscriptions = new Map();
```

When component is mounted you could do:

```typescript
  cls.prototype.connectedCallback = function() {

    // Override subscribe method so we can set subscription to new Map() later when component is unmounted we can unsubscribe
    Object.keys(this).forEach(observable => {
      if (isObservable(this[observable])) {
        const original = this[observable].subscribe.bind(this[observable]);
        this[observable].subscribe = function(cb: any) {
          const subscribe = original(cb);
          cls.subscriptions.set(subscribe, subscribe);
          return subscribe;
        };
      }
    });
  }
```

Then when component is unmounted

```typescript
cls.subscriptions.forEach(sub => sub.unsubscribe());
```


Working version https://github.com/rxdi/lit-html/commit/788a66dfa35303884c8edca6f9cde0e2cc065408#diff-94a4d8acf1c6ed64d5392eaeec2daf3dR133

Regards!

**Comment by yorrd** [comment]
@Stradivario this assumes that you have all observables as class fields, right? Not really an option for us, but a really cool approach if that's doable for you!

**Comment by Stradivario** [comment]
@yorrd correct it works only for private members of the class and not for static ones. It is a bit of a an ugly solution now since it is working with only one case but anyway it is good that it works! 

I am thinking also that using static observables inside a template can give you an really unpredicted results and it is not easy testable.I really like this approach:

```typescript

import { html, Component, async, LitElement } from '@rxdi/lit-html';
import { timer } from 'rxjs';
import { map } from 'rxjs/operators';

/**
 * @customElement about-component
 */
@Component({
  selector: 'about-component',
  template(this: AboutComponent) {
    return html`
      <header>
        <h1>About</h1>
      </header>
      ${async(this.timer)}
      <p>
        <img
          src="https://www.w3schools.com/html/pic_trulli.jpg"
          alt="Italian Trulli"
        />
      </p>
    `;
  }
})
export class AboutComponent extends LitElement {
  private timer = timer(1, 1000).pipe(map(v => v));
}
```

Since you can test it really easy

```typescript
import 'jest';
import { Container, createTestBed } from '@rxdi/core';
import { AboutComponent } from './app.component';

describe('Component', () => {
  let aboutComponent: AboutComponent;
  beforeAll(async () => {
    await createTestBed({
      components: [AboutComponent]
    }).toPromise();
   aboutComponent = Container.has(AboutComponent);
  });

  it('should be defined', done => {
    expect(aboutComponent).toBeTruthy();
    expect(
    done();
  });

  it('timer property should be observable', done => {
    expect(aboutComponent.timer).toBeInstanceOf(Observable);
    done();
  });
});

```

Regards!
