### ISSUE TITLE
Declarative event handling

### ISSUE THREAD

**Issue by lastmjs** [PolymerLabs/lit-html#13]
What will it take to get declarative event handling to work with this library?

**Comment by justinfagnani** [comment]
Take a look at https://github.com/PolymerLabs/lit-html/blob/master/src/labs/lit-extended.ts

That supports property settings and declarative events.

There's a small catch due to lit using function values as an extension point. Because functions are invoked by lit, if you want to pass a function into something you have to wrap it in a no-op function. This is something I'll look at to smooth out.

```js
let clickHandler = (e) => console.log('clicked!');
html`
  <button on-click=${_=>clickHandler}>Click Me</button>
`;
```

**Comment by justinfagnani** [comment]
Ok, I think we can close this now. I'll continue to work on docs to make this clearer.

**Comment by lastmjs** [comment]
I'm just trying it all out, and it's working in simple examples, and it's amazing. I have an idea I'd like to propose. Why not just allow the `on` properties to be set like any other properties? The native html elements that have `on` properties would just work, and custom elements that want event handlers would just need to define `on` properties that trigger the code to set up the event handling. That seems better than creating a custom `on-` syntax. What do you think?

**Comment by lastmjs** [comment]
I think that's the way I'm going to go, it seems to be working. I see no need for a custom `on-` syntax. It would be nice to get rid of the no-op function if possible. This is amazing!

**Comment by lastmjs** [comment]
And by the way, the .js files weren't transpiled, and I was like "no!", but then I was like "I'll make a quick change to my Zwitterion server to just automatically transpile JS as wel as TS": https://github.com/lastmjs/zwitterion Worked great.
