### ISSUE TITLE
Comparable with HTML Template Instantiation?

### ISSUE THREAD

**Issue by daKmoR** [PolymerLabs/lit-html#207]
hey,

I just saw this proposal 
https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Template-Instantiation.md

in theory it seem too use a "sort of" similar approach right?
in the far feature it may be used internally?

**Comment by justinfagnani** [comment]
They're definitely based on the same ideas, I was involved in the discussion that lead to the proposal. That shows will allow lit to be a lot smaller and hopefully faster.

We'll be contributing to a polyfill and then refactor lit-html so that it can work on the polyfill and ultimately on native implementations.

**Comment by daKmoR** [comment]
awesome :) thx for the info :) seems a bright future :)
