### ISSUE TITLE
Piecharts data binding error

### ISSUE THREAD

**Issue by miki996** [PolymerLabs/lit-html#220]
I am loading HTML code for piecharts through lit-html. When i load the HTML code for the piecharts through lit-html like a module i cannot see the piecharts. 

The scripts that should bind the data into the piecharts canvas are giving error that the canvas is not loaded in the document body.

When i go in the inspect element i cannot see the canvas loaded or drawn. Wondering how can i work this around.

Any help is welcomed!

**Comment by justinfagnani** [comment]
I'm having trouble understanding this issue here. lit-html doesn't do any loading of HTML, so I'm guessing that you mean that you have some boilerplate HTML in a lit template that's supposed to make a pie chart with a specific library?

Could you post a reproduction of the problem somewhere, or at least say which library you're using and what your template looks like?

**Comment by miki996** [comment]
Thanks for the response. Actually we solved this a while ago. Now i am trying to implement the charts on the dashboard. I'll let you know if i need help. I'm gonna post my solution and explain the issue in detail when i'm done.

**Comment by daKmoR** [comment]
it's solved then? if so could you pls close this issue. thx :)

PS: you can always reopen or create a new one if something new pops up

**Comment by miki996** [comment]
No problem. 

Thanks
