### ISSUE TITLE
repeat updates more then map?

### ISSUE THREAD

**Issue by daKmoR** [PolymerLabs/lit-html#230]
if I have the following code

```js
  import { html, render } from '../node_modules/lit-html/lit-html.js';
  import { repeat } from '../node_modules/lit-html/lib/repeat.js';

  let items = [];
  for (var i = 0; i < 10; i++) {
    items.push({ text: "Example " + Math.random(), "id": i });
  }
  const container = document.getElementById('container');

  const template = (items) => html`
    ${repeat(items, (el) => el.id, (el, index) => html`
      <div>
        <span>stuff</span><span>${el.text}</span>
      </div>
    `)}

    <hr />

    ${items.map(el => html`
      <div>
        <span>stuff</span><span>${el.text}</span>
      </div>
    `)}
  `;

  render(template(items), container);
  
  setTimeout(clearInterval, 100000, setInterval(function () {
    // let item = items.shift();
    // items.push(item);

    // swap items
    let b = items[2];
    items[2] = items[3];
    items[3] = b;    
  
    render(template(items), container);
  }.bind(this), 1000));
```
Code is also here:
https://github.com/daKmoR/lit-html-demos/blob/master/demo/repeat.html

I'm using latest master of lit-html and I do get a result like that

![repeat](https://user-images.githubusercontent.com/24378/34042393-ce8f7330-e19c-11e7-85c3-5e278e3815d6.gif)

so the full div get's updated every time with repeat... only the inner content gets updated with using map...

I'm not sure if that is intended? Is it faster to "swap" a node or to update the inner elements?

or is it a too simple example to see the benefit of repeat?

**Comment by bgotink** [comment]
For a simple example like this repeat might be overengineered, but in a more complicated example there is a significant benefit as repeat simply swaps the two nodes instead of updating every part of the two items instead. The effort for repeat is O(1) while the effort for the map function is O(n) where n is the number of parts in the item's template. The performance difference grows even more if you're using multiple templates based on the item, e.g. something like

```js
const template = followingList => html`<div class="following">
  ${repeat(followingList, user => user.id, user => {
    if (user.isBlocked) {
       return html`<div class="user user--blocked">
        <img src="/img/user_blocked.svg">
        <span class="name">${user.name}</span>
        <button on-click=${() => unblock(user)}>unblock</button>
      </div>`
    } else {
      return html`<div class="user">
        <img src=${user.pictureUrl}>
        <span class="name">${user.name}</span>
      </div>`;
    }
  })}
</div>`
``` 

If we now start swapping a blocked user and a regular user in the followingList, there's a huge difference in DOM manipulations:

- `repeat` swaps the two DOM nodes
- `Array#map` removes the two items, then creates and inserts new DOM to match the new items.

**Comment by daKmoR** [comment]
oh that is still open...

thanks for clarifying @bgotink :)
