### ISSUE TITLE
Better ergonomics around Function values

### ISSUE THREAD

**Issue by justinfagnani** [PolymerLabs/lit-html#29]
Function values are a sharp edge of the API. It's very easy to pass a function to a template expecting it to be used as an event handler, when instead it's invoked immediately as a template extension.

One possible way around this is to not invoke functions during rendering unless they have a special property, which could be set by a utility function:

```typescript
import { directive } from '../lit-html.js';

export repeat = directive((part: NodePart) => { ... }
```

Since function literals written by template authors are probably going to be written many, many times more than directives, it makes sense to optimize for their experience.

The one downside it this makes guarded (exception-safe) expressions longer. We'd have to vend a directive that ran a function immediately in a try/catch block:

```typescript
html`<input value=${safe(_=> this.foo.bar)}></input>`;
```

**Comment by justinfagnani** [comment]
wdyt @sorvell @kevinpschaaf @cdata @bicknellr?

**Comment by cdata** [comment]
On an intuitive level I agree that it is better to optimize for the event handler use case (and also passing functions as values in a more general sense). That said, it might be nice to document the various use cases we are aware of for immediate-invocation and function-as-value just to make sure.

Also, I like the `directive` helper in both concept and name.

**Comment by justinfagnani** [comment]
Event handlers is the big use case. I'd guess they're easily several orders of magnitude more common than directive (counting writing them only).

**Comment by justinfagnani** [comment]
I'm going to make up a PR for this, because documenting the current situation is painful.

**Comment by cdata** [comment]
Another argument in favor of this switch: it is easier to be concise about intended invocation context for event listeners. For example, let's say I want to handle a button click in my template:

```javascript
{
  render() {
    return html`
<button on-click="${() => this.onButtonClick}">Click me!</button>
`;
  }

  onButtonClick(event) {
    // What do you expect "this" to be?
  }
}
```

Presently, lit-extended invokes event handlers with [the target element as the context](https://github.com/PolymerLabs/lit-html/blob/master/src/lib/lit-extended.ts#L143). In order to get the desired `this` (for many common cases), I would have to change my binding to something like...

```javascript
html`<button on-click="${() => event => this.onButtonClick(event)}"></button>`;
```

Ideally, the handler invocation context should be set by the author who is registering the handler. @justinfagnani 's proposal above would enable a more concise expression of what I would probably want:

```javascript
html`<button on-click="${event => this.onButtonClick(event)}"></button>`;
```
