### ISSUE TITLE
Consider splitting up lit-extended

### ISSUE THREAD

**Issue by matthewp** [PolymerLabs/lit-html#41]
Hey! Great library, I've very excited about it. I was wondering if you would be open to splitting up lit-extended into the PropertyPart and EventPart functionality. I would like to use EventPart but not PropertyPart (instead of requiring a special syntax for attributes I'd rather use an `in` check personally).  Not sure how easy this would be to do... it's small enough code that I might just copy/paste into my own project if it's too much work to break these apart.

**Comment by justinfagnani** [comment]
I can maybe do that, though lit-extended is intended to be more of an example of one possible flavor of templates... forking it would not be bad.

But, I have to try to lobby against an `in` check for determining whether to set an attribute or property :) `in` checks don't work properly for custom elements upgrades. If an element instance is created  before being defined, it would have properties, possibly complex properties, set as string attributes, then at upgrade it would be reading strings instead of objects. That's obviously bad for objects that don't have a full fidelity string representation, but even for values that do, it can mess with object identity that might be used for dirty-checking and pruning update work.

**Comment by matthewp** [comment]
Yeah, I know this problem, it's something I would use on my own apps that I have control over and can prevent those mistakes. It's not something I'm going to attempt to make popular or share publicly.

My issue with how lit-extended does properties is I don't want to pepper my templates with a lot of `$` because the vast majority of my templates are spans, lis, and divs, and attributes are what I am mostly setting on those, so having properties be the default is not something I agree with. So I'm glad this behavior is not in core.

**Comment by matthewp** [comment]
If I were going for a syntax approach I would add a prefix/suffix for the property case rather than the attribute case. But if others prefer the latter, that's fine. I think copy/pasting the EventPart class into my own code and writing my own `render` will work fine.

**Comment by justinfagnani** [comment]
Sounds good. At this point I'd actually like to see some variation here to possibly test the extension points out for ergonomics. I'm considering changing the way `render()` is implemented so you can just provide a callback, rather than re-implement and subclass TemplateInstance.
