### ISSUE TITLE
Tests don‘t test anything

### ISSUE THREAD

**Issue by surma** [PolymerLabs/lit-html#79]
The tests currently don’t run at all.

Adding `-p` to the `wct` invocation shows that some libraries don’t load and as a result no tests are being run.

![screen shot 2017-08-31 at 12 06 45 pm](https://user-images.githubusercontent.com/234957/29920335-f217a256-8e44-11e7-8cb7-bf2a5e3c9c6e.png)

**Comment by justinfagnani** [comment]
Those errors are because we're still working on WCT for modules/npm and some of the WCT's automatically added dependencies aren't installed. They don't cause failures though, and the tests are running for me locally and on CI: https://travis-ci.org/PolymerLabs/lit-html 89 passing on master and they definitely fail for PRs that get something wrong.

What version of WCT are you running?

**Comment by surma** [comment]
Huh, I just ran `npm i` (so `wct` is at 6.0.1) and it didn’t work. I just re-did that on a completely fresh clone and same thing is happening. I’ll investigate – if it runs on CI  the problem is probably on my end.

**Comment by surma** [comment]
As far as I can tell, mocha/wct finishes before the tests have been loaded asynchronously. Seems like we are in some kind of race-condition here. I’ll see if I can reliably delay wct until the tests are loaded.

**Comment by surma** [comment]
Never mind, not a race condition, but wct prefers Chrome Stable over Canary, which doesn’t have modules. Manually opening the tests in Canary makes them work. I’ll look into ensuring it’s Canary, although this might not be worth it considering M61 is around the corner. Closing this for now.

**Comment by surma** [comment]
For completeness sake: I used `-l canary` for the time being.
